import Std

namespace Teichmuller

/-!
The first formal layer is deliberately structural. It records the objects
needed by Teichmüller's 1944 program without pretending that topology,
holomorphicity, or the measurable Riemann mapping theorem have already been
formalized here.

The three historical ingredients are represented by:

* `MarkedRiemannSurface`: topological determination (a marking);
* `AnalyticFamily`: a family of surfaces over a base;
* `TurningPieceCoordinate`: a parameterized local deformation interface.

The analytic predicates are fields of type `Prop`. They are specifications,
not axioms asserting that the relevant analytic constructions exist.
-/

/-- The topological data of a surface, kept abstract in the core layer. -/
structure TopologicalSurface where
  carrier : Type
  hausdorff : Prop
  secondCountable : Prop
  connected : Prop
  locallyEuclidean : Prop

/-- A placeholder for a compatible complex atlas on a surface. -/
structure ComplexStructure (S : TopologicalSurface) where
  charts : Type
  compatible : Prop
  complexDimensionOne : Prop

/-- A Riemann surface as topological and complex-analytic data. -/
structure RiemannSurface where
  underlying : TopologicalSurface
  complex : ComplexStructure underlying

/-- A bijection with an explicit inverse. -/
structure Homeomorphism (X Y : Type) where
  toFun : X → Y
  invFun : Y → X
  left_inv : ∀ x, invFun (toFun x) = x
  right_inv : ∀ y, toFun (invFun y) = y

namespace Homeomorphism

instance : CoeFun (Homeomorphism X Y) (fun _ => X → Y) :=
  ⟨Homeomorphism.toFun⟩

def refl (X : Type) : Homeomorphism X X where
  toFun := id
  invFun := id
  left_inv := by intro x; rfl
  right_inv := by intro x; rfl

def symm (f : Homeomorphism X Y) : Homeomorphism Y X where
  toFun := f.invFun
  invFun := f.toFun
  left_inv := f.right_inv
  right_inv := f.left_inv

def comp (g : Homeomorphism Y Z) (f : Homeomorphism X Y) : Homeomorphism X Z where
  toFun := fun x => g.toFun (f.toFun x)
  invFun := fun z => f.invFun (g.invFun z)
  left_inv := by
    intro x
    change f.invFun (g.invFun (g.toFun (f.toFun x))) = x
    rw [g.left_inv]
    exact f.left_inv x
  right_inv := by
    intro z
    change g.toFun (f.toFun (f.invFun (g.invFun z))) = z
    rw [f.right_inv]
    exact g.right_inv z

@[simp] theorem comp_apply (g : Homeomorphism Y Z) (f : Homeomorphism X Y) (x : X) :
    comp g f x = g (f x) := rfl

@[simp] theorem refl_apply (x : X) : refl X x = x := rfl

end Homeomorphism

/-- A biholomorphic map, with analytic conditions left as propositions. -/
structure ConformalEquiv (X Y : RiemannSurface) where
  toHomeomorphism : Homeomorphism X.underlying.carrier Y.underlying.carrier
  holomorphic : Prop
  inverseHolomorphic : Prop

/-- A marked Riemann surface over a fixed topological carrier `S`. -/
structure MarkedRiemannSurface (S : Type) where
  surface : RiemannSurface
  marking : Homeomorphism S surface.underlying.carrier

/--
The equivalence relation generated by conformal equivalence compatible with
the marking up to isotopy. Its three laws are supplied by the geometric
theory in a later layer.
-/
class MarkingRelation (S : Type) where
  related : MarkedRiemannSurface S → MarkedRiemannSurface S → Prop
  refl : ∀ X, related X X
  symm : ∀ {X Y}, related X Y → related Y X
  trans : ∀ {X Y Z}, related X Y → related Y Z → related X Z

instance markedSetoid (S : Type) [MarkingRelation S] :
    Setoid (MarkedRiemannSurface S) where
  r := MarkingRelation.related
  iseqv := {
    refl := MarkingRelation.refl
    symm := by
      intro X Y h
      exact MarkingRelation.symm h
    trans := by
      intro X Y Z hXY hYZ
      exact MarkingRelation.trans hXY hYZ
  }

/-- The quotient of marked surfaces: the formal core of Teichmüller space. -/
def TeichmullerSpace (S : Type) [MarkingRelation S] :=
  Quotient (markedSetoid S)

def teichmullerPoint (X : MarkedRiemannSurface S) [MarkingRelation S] :
    TeichmullerSpace S :=
  Quotient.mk' X

theorem teichmullerPoint_eq_of_related
    [MarkingRelation S] (X Y : MarkedRiemannSurface S)
    (h : MarkingRelation.related X Y) :
    teichmullerPoint X = teichmullerPoint Y := by
  exact Quotient.sound h

/-- A family of Riemann surfaces over an abstract base. -/
structure AnalyticFamily where
  base : Type 1
  total : Type 1
  projection : total → base
  fibre : base → RiemannSurface
  familyAxiom : Prop

/-- The universal-family interface of the original moduli problem. -/
structure UniversalFamily (S : Type) [MarkingRelation S] where
  family : AnalyticFamily
  classifyingPoint : MarkedRiemannSurface S → family.base
  universalProperty : Prop

/--
A local turning-piece coordinate. The parameter space and locality condition
are abstract at this stage; the analytic realization will be added later.
-/
structure TurningPieceCoordinate (S : Type) where
  reference : MarkedRiemannSurface S
  parameter : Type
  zero : parameter
  coordinate : parameter → MarkedRiemannSurface S
  atZero : coordinate zero = reference
  locality : Prop

end Teichmuller
